# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-10.15, windows-2019 ]
        java: [ 11, 15, 16 ]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    name: Java ${{ matrix.java }} ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Gradle task
      run: ./gradlew generateGitProperties
